name = "Gravel"
license = "MIT"
licenselink = "https://github.com/kowalevski/hugo-gravel/blob/main/LICENSE.md"
description = "A simple theme for Hugo"
homepage = "https://github.com/kowalevski/hugo-gravel"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "multilingual",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.77.0"

[author]
name = "Max Kovalevsky"
homepage = "https://kowalevski.com"
